function [tdata, lasDisp, ref, ctrl] = importCLdata(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TDATA, LASDISP, REF, CTRL] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [TDATA, LASDISP, REF, CTRL] = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [tdata, lasDisp, ref, ctrl] = importfile("C:\Users\vasu1\Documents\2. CU Second Year\1. AMTL\1. CPS Project\4. Code\4. CL Control\CL_ctrl_lasDisp\CLdata_lasDisp_093019\sensor0.log", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Oct-2019 12:50:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["V_Tot", "V_Rm", "theta", "Ca"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
tdata = tbl.tdata;
lasDisp = tbl.lasDisp;
ref = tbl.ref;
ctrl = tbl.ctrl;
end